<?php



// ETAPE1: DECLARER/CREER SA FONCTION
// ON PEUT AJOUTER DES PARAMETRES A LA FONCTION
// => LES VALEURS DE CES PARAMETRES SERONT FOURNIES AU MOMENT DE L'APPEL DE LA FONCTION
// => LES PARAMETRES SONT DES ENTREES
function additionner($param1, $param2)
{
    // CORPS DE LA FONCTION
    // CODE EN ATTENTE D'ETRE EXECUTE
    // SI ON VEUT ADDITIONNER LES 2 NOMBRES EN PARAMETRES
    $resultat = $param1 + $param2;

    // SORTIE: ON PEUT RENVOYER UNE VALEUR EN RESULTAT DE LA FONCTION
    return $resultat;
    // return ARRETE LE CODE DE LA FONCTION
    // CA NE SERT A RIEN DE RAJOUTER APRES UN return
    // echo "FIN";
}

echo "<h4>12 + 34</h4>";
// ETAPE2: ET ENSUITE POUR ACTIVER LE CODE
// ON APPELLE LA FONCTION
echo additionner(12, 34);    // PHP ATTRIBUE LES VALEURS AUX PARAMETRES 
// $param1 = 12 ET $param2 = 34
echo "<h4>3 + 2</h4>";
echo additionner(3, 2);     // PHP ATTRIBUE LES VALEURS AUX PARAMETRES 
// $param1 = 3 ET $param2 = 2

echo "<h4>EXO CALCULER PRIX TTC</h4>";
// EXERCICE TVA
// CREER UNE FONCTION QUI PREND 2 PARAMETRES $prixHT ET $tauxTVA
// ET QUI RENVOIE COMME RESULTAT LE PRIX TTC
// ET ENFIN POUR VERIFIER ON FERA UN TEST AVEC $prixHT = 50 ET $tauxTVA = 20
// ETAPE1: CREER LA FONCTION
function calculerTTC($prixHT, $tauxTVA)
{
    // TRAVAIL COMPLIQUE: CODER LA FONCTION
    $resultat = $prixHT + $prixHT * $tauxTVA / 100;
    return $resultat;
}

// ETAPE2: APPELER LA FONCTION AVEC LES VALEURS DE TEST
echo "<hr>";
echo calculerTTC(50, 20);   // TRAVAIL FACILE: UTILISER LA FONCTION
echo "<hr>";

echo "<h4>EXO CALCULER PRIX TTC</h4>";

$resultat = calculerTTC(150, 20);
echo "<h5>VOICI LE RESULTAT $resultat</h5>";




// SIMPLIFICATION
// ON PEUT NE PAS METTRE LA BALISE FERMANTE PHP